#!/bin/sh
### BEGIN INIT INFO
# Provides: 
# Required-Start:
# Required-Stop: 
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop radarMonitor
# Description: radarMontor is a node project used to report speeds from a Stalker II Pro OEM sensor
### END INIT INFO
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export SERVER_PORT=80

case "$1" in
  start)
  exec forever /var/radar/service/forever.json
  ;;

  stop)
  exec forever stop radarMonitor
  ;;
esac

exit 0
