#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          radarMonitor
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop radarMonitor
# Description: radarMontor is a node project used to report speeds from a Stalker II Pro OEM sensor
### END INIT INFO
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules


start() {
    echo "Starting radarMonitor node instance: "
    forever --uid radarMonitor --sourceDir=/var/radar -p /var/radar/service -l /var/radar/service/radarMonitor.log -a --minUptime 1000 --spinSleepTime 60000 start app.js
    exit 0
}

stop() {
    echo -n "Shutting down radarMonitor node instance : "
    forever stop radarMonitor
    exit 0
}

case "$1" in
    start)
        start
	exit 0
        ;;
    stop)
        stop
	exit 0
        ;;
    *)
        echo "Usage:  {start|stop}"
        exit 1
        ;;

esac

exit 0
